robot_base_frame: base_link

transform_tolerance: 0.5

footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]
footprint_padding: 0.01
robot_radius: 0.30

robot_radius: 0.30
inflater:
#  robot_radius: 0.30
  inflation_radius: 0.70

# Obstacles are defined in robot folders
